server:
  port: 3344



spring:
  application:
    name: cloud-config

  cloud:
    config:
      server:
        git:
          uri: https://github.com/tongchunpan/cloud-config.git   #git 上的地址

          #搜索目录
          search-paths:
            - cloud-config
          #读取分支
          force-pull: true
          username: 1809872737@qq.com
          password: tcp2511byl
      label: master

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
     defaultZone: http://localhost:7001/eureka
